#name: zhangsan \n lisi
#student:
#  name: 张三
#  age: 20
#  pets:
#    dog
#    cat
#    pig
universityName: 重庆文理学院

student1:
  name: 张三
  age: 20
teacher: superman
school:
  - ${teacher}:人工智能学院
  - ${teacher}:大数据学院

students: [{name: 张三,age: 20},{name: 李四,age: 19}]
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmbuild?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sxy20000609.
    type: com.alibaba.druid.pool.DruidDataSource

  security:
    user:
      name: tom
      password: 123

  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8083

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


